Feature: Generate report
    Description: A report is generated by the project leader
    Actors: project leader



    Scenario: A report is generated susccesfully

        Given the system contains a worker with name "Bob Hansen", ID "ABCD"
        And the system contains a project with name "Project1", number "030901"
        And the worker is project leader
        When the project leader generates a report
        Then the report is succesfully generated

    Scenario: A report is not generated

        Given the system contains a worker with name "Bob Hansen", ID "ABCD"
        And the system contains a project with name "Project1", number "030901"
        And the worker is not the project leader
        When the worker generates a report
        Then the error message "You are not the project leader" is given


    Scenario: The report contains project leader name

        Given the system contains a worker with name "Bob Hansen", ID "ABCD"
        And the system contains a project with name "Project1", number "030901"
        And the worker is project leader
        When A report is generated succesfully
        Then the report is opened
        And the report contains project leader
