Feature: Generate report
Description: A report is generated by the project leader
Actors: project leader


Scenario: A report is generated susccesfully

Given there is a project with title "Extreme Programming", ID 0001
And the project exist in the system
And the worker with Name "Anders" "Andersen" and ID "AAAA" is assigned project leader of the project with ID 0001
When the project leader generates a report
Then the text is given "Extreme Programming 1\nAndersen, Anders AAAA"

#     Scenario: A worker tries to generate report
#         Given there is a project with title "Extreme Programming", ID 0001
#         And the worker with ID "AAAA" is not the project leader of the project with ID 0001
#         When the worker generates a report
#         Then the error message "You are not the project leader" is given